### ISSUE TITLE
Mobs cannot spawn on stone nodes in the darkness?

### ISSUE THREAD

**Issue by WSDguy2014** [sfan5/minetest_classic#12]
I noticed the issue when I finally started to experiment with how mob spawning works.
During the testing, I likely found out that in the original 0.3 version, mobs also spawn in the caves (appears standing on stone nodes), not just in 'dungeons' as it is mentioned in the comment.
![image](https://github.com/user-attachments/assets/95d14757-45b2-416a-8475-a5388a023296)
Did you really missed another one in the node names list during the process of rewriting the code from C++ to Lua?

**Comment by sfan5** [comment]
Looks like I was careless translating the names. Mobs spawn on *stone* and mossy cobble, not *cobble* and mossy cobble.
Explains why mobs are so hard to find too...
