### ISSUE TITLE
Why is there a '3d_clouds' option in 'Modernize flags' section?

### ISSUE THREAD

**Issue by WSDguy2014** [sfan5/minetest_classic#15]
It felt pointless in my opinion, because this option already exists since original 0.3.1 version according to changelog.txt doc file (but not here on version 0.3).
It felt pointless to me, I don't know what's the point of having that separate visual enhancement option included in **Modernize flags** list when it's already available in `Graphics and Audio -> Graphics` settings section?
Client with 3D clouds enabled, but the server has 3D clouds disabled, client in the server would still be observing 2D flat clouds?

Also within the same changelog.txt doc file, 'Opaque water' on/off graphics option is also available in original **0.3.1** version, but not included in this game because this setting already exists (as 'Opaque liquids') in the same `Graphics and Audio -> Graphics -> Graphics Effects` section.

What about redirecting those options? (Opaque liquids, Smooth lighting, Digging particles, Enable console window, 3D clouds and probably others)

**Comment by sfan5** [comment]
What led me to do this is that MT0.3 has 3D clouds disabled by default and I thought the out-of-the-box experience should be closer.

But you're right that the client already has a setting for this or the opaque water.
I guess I should remove the flag again.

>  Client with 3D clouds enabled, but the server has 3D clouds disabled, client in the server would still be observing 2D flat clouds?

correct

**Comment by sfan5** [comment]
c241e0a7a6c1383d823e126b8969df1f845798be
