### ISSUE TITLE
More by-default texture pack support

### ISSUE THREAD

**Issue by GoodClover** [sfan5/minetest_classic#17]
Most items are shared with Minetest Game, which uses a `default_` prefix for textures, so texture packs follow this.
However here, textures don't have this prefix, so texture packs don't work by default (have to write a overrides.txt for them, shame games/mods can't supply one).

For most textures this shouldn't be an issue, but for example `torch_*` is `torch_*_animated` in MTG.
Would maybe have to use a texture modifier or similar to disable it (with a modernisation option for re-enabling?).

**Comment by sfan5** [comment]
see https://github.com/sfan5/minetest_classic/pull/18#issuecomment-2439746306
