### ISSUE TITLE
When i spawn mobv2 it says a error failed to synthax data or something, looked in the code found nothing useful, plus hes different if i spawn him he is stone. 

### ISSUE THREAD

**Issue by nininik0** [sfan5/minetest_classic#3]
Do /spawnentity default:Mobv2

**Comment by nininik0** [comment]
Oh and oerkki and dungeonmaster dissapear at artificial light put use_texture_alpha = true into code (I did it and it worked)

**Comment by nininik0** [comment]
Also the player dissappear near a artificial light source

**Comment by sfan5** [comment]
> When i spawn mobv2 it says a error failed

You can't spawn them manually.

> oerkki and dungeonmaster dissapear at artificial light

> player dissappear near a artificial light source

works for me.

**Comment by nininik0** [comment]
Wait, but the player dissappears near artificial light source

**Comment by sfan5** [comment]
No, works correctly for me.

**Comment by nininik0** [comment]
Ok, must be some of my client side glitch also thanks for clearing up the confusion about mobv2
