### ISSUE TITLE
Jungle grass node renders texture differently.

### ISSUE THREAD

**Issue by WSDguy2014** [sfan5/minetest_classic#9]
- **Game version:** 2024-07-28 [MT 5.5+] 712 KB [b430f]
- **Engine version:** 5.8.0

Excited to see this game that recreates nostalgia gameplay experience in a modern-day, latest engine version.

About texture mapping difference for jungle grass is when I decided to try porting my Minecraft texture pack (or a texture mod I could say) that I made for an original 0.3(.1) version of Minetest a few years ago onto a new 5.8.0 engine version, most of the textures it renders correctly, some other textures are rendered incorrectly. I changed and tinkered some of the textures, I could also change the jungle grass texture, but it will not render properly the same way as it used to for the original 0.3 version.

I did a comparison with the original 0.3 version.
![image](https://github.com/user-attachments/assets/ce570410-9a69-439d-b632-e7fa9c651f28)
And a recreation.
![image](https://github.com/user-attachments/assets/14795732-60dd-4c97-ae77-45050b1c635c)
Here is my current settings for modernizing flags.
![image](https://github.com/user-attachments/assets/21f056aa-6742-4495-ba18-fda7a08871ef)
I made a test texture to align it for the original version, the highlights are:
- Green: visibly rendered
- Cyan: renders but will usually submerged into the ground
- Red: this part should not be rendered (only visibly displayed on an inventory item)
![junglegrass](https://github.com/user-attachments/assets/4d39ab0d-31f5-4e81-9067-8c5762a2d976)

I also noticed the way it renders textures in plant-like (cross-shaped X) nodes compared to the latest engine version with this game recreation.

https://github.com/user-attachments/assets/f406d7da-4eb8-4be6-add0-7058f5d9a3f6

While looking in the code, I noticed in the comments a _lot_ of to-do lists that you have to implement soon. Keep up good work and hopefully you will improve this game accurately recreating functions and features to make it a more accurate late-2011 gameplay experience.

**Comment by sfan5** [comment]
Junglegrass not being stretched correctly is indeed a known issue. This is an engine limitation (https://github.com/minetest/minetest/pull/12828, workarounds possible).

The fact that part of the texture is cut off is new to me and I don't know if I can emulate that sanely.
